/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_shenxing_caesar_hellojni_HelloJni */

#ifndef _Included_com_study_shenxing_caesar_hellojni_HelloJni
#define _Included_com_study_shenxing_caesar_hellojni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_shenxing_caesar_hellojni_HelloJni
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_study_shenxing_caesar_hellojni_HelloJni_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
