/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_shenxing_caesar_hellojni_JniTestActivity */

#ifndef _Included_com_study_shenxing_caesar_hellojni_JniTestActivity
#define _Included_com_study_shenxing_caesar_hellojni_JniTestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_shenxing_caesar_hellojni_JniTestActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_study_shenxing_caesar_hellojni_JniTestActivity_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
