//
// Created by 沈星 on 06/02/2017. c文件名称可以随意，只要编译后的so库文件一致即可
// 此C文件可以直接拷贝生成的头文件 或者 通过 #include "com_study_shenxing_caesar_hellojni_JniTestActivity.h" 引入 然后直接copy native函数并实现即可
//



/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_shenxing_caesar_hellojni_JniTestActivity */

#ifndef _Included_com_study_shenxing_caesar_hellojni_JniTestActivity
#define _Included_com_study_shenxing_caesar_hellojni_JniTestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_shenxing_caesar_hellojni_JniTestActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_study_shenxing_caesar_hellojni_JniTestActivity_getStringFromNative
        (JNIEnv * env, jobject obj) {

    return (*env)->NewStringUTF(env, "hello From Jni");
}

#ifdef __cplusplus
}
#endif
#endif